language: python
python:
  - "3.4"
addons:
  postgresql: "9.3"
install:
  - pip install wheel
  - pip install -r requirements.txt
  - pip install -r requirements-testing.txt
  - npm install
before_script:
  - createdb -U postgres pastry
  - python manage.py migrate --noinput
  - python manage.py createsuperuser --username=travis --email=travis@localhost --noinput
script:
  - make dist
  - tox
notifications:
  slack:
    secure: OLiZ0jS9jFQNLu31QwvVozFP73zee06bEXCziWLDA9lmkdhiQ1rGwTjsFXMG6tHhu23cKqvQNBtdaIXCMEY1fPGoeo4ja5R7wH7lCUFSqYFatFkYO2s9mDzLtMcxfN+VGrNfjHKT/zfpYFBMlXSLDOXNNYRPQ2zAWch6D9vUk48=
